/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Dotnet FE Auth
 * OpenAPI spec version: v1
 */
import { HttpClient } from '@angular/common/http';
import type { HttpContext, HttpEvent, HttpParams } from '@angular/common/http';

import type {
  HttpHeaders,
  HttpResponse as AngularHttpResponse,
} from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import type { Observable } from 'rxjs';

export type ErrorResponseErrors = { [key: string]: string[] };

/**
 * the dto used to send an error response to the client
 */
export interface ErrorResponse {
  /** the http status code sent to the client. default is 400. */
  statusCode?: number;
  /** the message for the error response */
  message?: string;
  errors?: ErrorResponseErrors;
}

export interface LoginRequest {
  /**
   * @minLength 1
   * @pattern ^[^@]+@[^@]+$
   */
  email: string;
  /** @minLength 1 */
  password: string;
}

export interface LoginResponse {
  token: string;
}

export interface MyRequest {
  firstName: string;
  lastName: string;
  age?: number;
}

export interface MyResponse {
  fullName: string;
  isOver18?: boolean;
}

export interface ValidateTokenResponse {
  email: string;
}

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
    | HttpParams
    | Record<
        string,
        string | number | boolean | Array<string | number | boolean>
      >;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

@Injectable({ providedIn: 'root' })
export class DotnetFEAuthService {
  private readonly http = inject(HttpClient);
  login<TData = LoginResponse>(
    loginRequest: LoginRequest,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  login<TData = LoginResponse>(
    loginRequest: LoginRequest,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  login<TData = LoginResponse>(
    loginRequest: LoginRequest,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  login<TData = LoginResponse>(
    loginRequest: LoginRequest,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/api/login`, loginRequest, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/api/login`, loginRequest, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.post<TData>(`/api/login`, loginRequest, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  createuser<TData = MyResponse>(
    myRequest: MyRequest,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  createuser<TData = MyResponse>(
    myRequest: MyRequest,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  createuser<TData = MyResponse>(
    myRequest: MyRequest,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  createuser<TData = MyResponse>(
    myRequest: MyRequest,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/api/user/create`, myRequest, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/api/user/create`, myRequest, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.post<TData>(`/api/user/create`, myRequest, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  validatetoken<TData = ValidateTokenResponse>(
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  validatetoken<TData = ValidateTokenResponse>(
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  validatetoken<TData = ValidateTokenResponse>(
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  validatetoken<TData = ValidateTokenResponse>(
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/validate-token`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/validate-token`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get<TData>(`/api/validate-token`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }
}
