@dotnet_fe_auth_HostAddress = http://localhost:5085

POST {{dotnet_fe_auth_HostAddress}}/api/login
Accept: application/json

{
  "Email": "any@mail.com",
  "Password": "SecureDevPassword123!"
}
###
