AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Nx distributed cache infrastructure using AWS S3 and GitHub Actions OIDC'

Parameters:
  AppName:
    Type: String
    Default: 'nx'
    Description: Application name for resource naming
    AllowedPattern: '^[a-z0-9-]+$'
    ConstraintDescription: Must contain only lowercase letters, numbers, and hyphens
  
  Environment:
    Type: String
    Default: 'prod'
    Description: Environment name
    AllowedValues:
      - 'dev'
      - 'staging'
      - 'prod'
  
  RegionShorthand:
    Type: String
    Default: 'euw1'
    Description: Short region identifier (e.g., euw1 for eu-west-1)
    AllowedPattern: '^[a-z0-9]+$'
  
  GitHubOrganization:
    Type: String
    Default: 'EelcoLos'
    Description: GitHub organization name
    AllowedPattern: '^[a-zA-Z0-9-]+$'
  
  GitHubRepository:
    Type: String
    Default: 'nx-tinkering'
    Description: GitHub repository name
    AllowedPattern: '^[a-zA-Z0-9-]+$'
  
  Owner:
    Type: String
    Default: 'EelcoLos'
    Description: Resource owner
  
  CostCenter:
    Type: String
    Default: 'engineering'
    Description: Cost center for billing/tracking

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Resource Naming"
        Parameters:
          - AppName
          - Environment
          - RegionShorthand
      - Label:
          default: "GitHub Configuration"
        Parameters:
          - GitHubOrganization
          - GitHubRepository
      - Label:
          default: "Tagging"
        Parameters:
          - Owner
          - CostCenter

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']

Resources:
  # S3 Bucket for Nx Cache
  NxCacheBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppName}-${Environment}-${RegionShorthand}-cache'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldCacheObjects
            Status: Enabled
            ExpirationInDays: 30
            NoncurrentVersionExpirationInDays: 7
      Tags:
        - Key: Application
          Value: nx-cache
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: nx-tinkering
        - Key: Owner
          Value: !Ref Owner
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: ManagedBy
          Value: CloudFormation

  # S3 Bucket Policy - Allow service account and root user access
  NxCacheBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref NxCacheBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowServiceAccountAccess
            Effect: Allow
            Principal:
              AWS: !GetAtt NxCacheServiceAccount.Arn
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !GetAtt NxCacheBucket.Arn
              - !Sub '${NxCacheBucket.Arn}/*'
          - Sid: AllowRootUserAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !GetAtt NxCacheBucket.Arn
              - !Sub '${NxCacheBucket.Arn}/*'

  # IAM Service Account (Dedicated managed identity for Nx cache access)
  NxCacheServiceAccount:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub '${AppName}-${Environment}-${RegionShorthand}-nx-cache'
      Tags:
        - Key: Application
          Value: nx-cache
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: nx-tinkering
        - Key: Owner
          Value: !Ref Owner
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: ManagedBy
          Value: CloudFormation

  # IAM Policy for S3 Access (minimal permissions only for this bucket)
  NxCacheServiceAccountPolicy:
    Type: AWS::IAM::UserPolicy
    Properties:
      PolicyName: !Sub '${AppName}-${Environment}-${RegionShorthand}-s3-cache-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3CacheAccess
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !GetAtt NxCacheBucket.Arn
              - !Sub '${NxCacheBucket.Arn}/*'
      UserName: !Ref NxCacheServiceAccount

Outputs:
  BucketName:
    Description: S3 bucket name for Nx cache
    Value: !Ref NxCacheBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  BucketArn:
    Description: S3 bucket ARN
    Value: !GetAtt NxCacheBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'

  ServiceAccountUsername:
    Description: IAM service account username (create Access Keys for this user)
    Value: !Ref NxCacheServiceAccount
    Export:
      Name: !Sub '${AWS::StackName}-ServiceAccountUsername'

  ServiceAccountArn:
    Description: IAM service account ARN
    Value: !GetAtt NxCacheServiceAccount.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ServiceAccountArn'

  StackName:
    Description: CloudFormation stack name
    Value: !Ref 'AWS::StackName'

  AwsAccountId:
    Description: AWS Account ID
    Value: !Ref 'AWS::AccountId'

  AwsRegion:
    Description: AWS Region
    Value: !Ref 'AWS::Region'
