name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      - run: npx nx-cloud start-ci-run --distribute-on="3 my-linux-dotnet-medium" --stop-agents-after="e2e-ci" --with-env-vars="DOTNET_ROOT"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - run: npm ci --foreground-scripts
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud" to record its logs to Nx Cloud
      - run: npx nx-cloud record -- nx affected -t lint test build e2e-ci
