name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      - run: npx nx-cloud start-ci-run --distribute-on="3 my-linux-dotnet-medium" --stop-agents-after="e2e-ci" --with-env-vars="DOTNET_ROOT"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud" to record its logs to Nx Cloud
      - run: npx nx-cloud record -- nx affected -t lint test build

      - name: Cache Playwright binary
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
      - name: Install playwright browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install
      - run: npx nx-cloud record -- nx affected --parallel 1 -t e2e-ci
