on:
  # Workflow_dispatch enables you to manually run this job
  workflow_dispatch:
  # It is also scheduled to run nightly. (mostly due to the last comment in this file)
  schedule:
    - cron: '0 0 * * *'
name: 'Labels: create declared labels'
permissions:
  contents: read
  issues: write
jobs:
  labels:
    name: Update Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: lannonbr/issue-label-manager-action@27295bcfbcb0c5480e9ab0d3b4b08ce5cd9d3bb9 # 5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # delete: true deletes undefined labels (in labels.yml) from your repository
          # This helps against creating a messy set of labels over a longer period of time.
          # To add labels, simply declare them in labels.yml, this way, its a team decision.
          delete: true
        continue-on-error: true
