name: 'PR: Dependabot auto-merge'
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number'
        required: false
        default: ''

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-check:
    name: 'Check dependency metadata'
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'EelcoLos'}}
    steps:
      - name: Fetch dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          skip-commit-verification: true
      - name: 'Run Nx Migrate if package is NX'
        if: ${{ github.event.action == 'opened' && steps.metadata.outputs.package-ecosystem == 'npm' && (contains(steps.metadata.outputs.dependency-names, '@nx/') || contains(steps.metadata.outputs.dependency-names, 'nx')) }}
        run: |
          nx_version=$(npm show @nx/workspace version)
          jq --arg version "$nx_version" '.version = $version' package.json > tmp.$$.json && mv tmp.$$.json package.json || echo "Failed to update package.json version" >&2
          npx nx migrate latest
          npx nx migrate --run-migrations --create-commits
      - name: 'Run Nx Migrate if package is @nx-dotnet/core'
        if: ${{ github.event.action == 'opened' && steps.metadata.outputs.package-ecosystem == 'npm' && (contains(steps.metadata.outputs.dependency-names, '@nx-dotnet/core')) }}
        run: |
          npx nx migrate @nx-dotnet/core
          npx nx migrate --run-migrations --create-commits
      - name: 'Enable auto-merge for minor/patch updates'
        id: enable-automerge
        # update-type is one of [ version-update:semver-major, version-update:semver-minor, version-update:semver-patch ]
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Review PR with approval'
        if: steps.enable-automerge.outcome == 'success'
        run: |
          gh pr review "$PR_URL" --approve --body "This dependency update can be auto-merged since it's a minor or patch version update."
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Comment on PR'
        if: steps.enable-automerge.outcome != 'success'
        run: |
          gh pr comment "$PR_URL" --body "This dependency update was not auto-merged as this is a major version update, please review manually."
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
